# load dataset

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('../dataset/shortjokes.csv')

In [5]:
text = '\n '.join(data['Joke'])

In [6]:
text[:10000]

'[me narrating a documentary about narrators] "I can\'t hear what they\'re saying cuz I\'m talking"\n Telling my daughter garlic is good for you. Good immune system and keeps pests away.Ticks, mosquitos, vampires... men.\n I\'ve been going through a really rough period at work this week It\'s my own fault for swapping my tampax for sand paper.\n If I could have dinner with anyone, dead or alive... ...I would choose alive. -B.J. Novak-\n Two guys walk into a bar. The third guy ducks.\n Why can\'t Barbie get pregnant? Because Ken comes in a different box. Heyooooooo\n Why was the musician arrested? He got in treble.\n Did you hear about the guy who blew his entire lottery winnings on a limousine? He had nothing left to chauffeur it.\n What do you do if a bird shits on your car? Don\'t ask her out again.\n He was a real gentlemen and always opened the fridge door for me\n Telling my daugthers date that "she has lice and its very contagious the closer you get to her." *Correct way to paren

# tokenization

In [7]:
! pip install tiktoken


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import tiktoken 

enc = tiktoken.encoding_for_model("gpt-4o")


In [9]:
enc.encode("hi there")

[3686, 1354]

In [10]:
enc.decode([3686, 1354])

'hi there'

In [11]:
import torch

In [12]:
data = torch.tensor(enc.encode(text), dtype=torch.long)
data[:1000]

tensor([    58,   1047,  18225,   1365,    261,  42555,   1078,  18225,   4840,
            60,    392,     40,   8535,   9598,   1412,  18940,  10326, 149051,
          5477,  11695,   1092,    353,   4481,    922,  13857,  42756,    382,
          1899,    395,    481,     13,   9700,  31907,   2420,    326,  18295,
         79832,   4194,   2600,   8736,     11,  22644, 168769,     11, 128429,
          1008,   1966,    558,   9790,   1339,   2966,   1819,    261,   2715,
         19595,   5265,    540,   1101,    495,   2384,   7744,    922,   2316,
         20795,    395, 132194,    922,  36993,   1362,    395,  10749,   6651,
           558,   1843,    357,   2023,    679,  16078,    483,   7545,     11,
          9224,    503,  23757,   1008,   2550,     40,   1481,   5655,  23757,
            13,    533,     33,   5005,     13, 169101,   7413,  13311,  11655,
          5229,   1511,    261,   3608,     13,    623,   6914,  12159, 132116,
           558,  12587,   8535, 104565, 

# Spliting Train and Validation data

In [13]:
n = int(0.9* len(data))
training_data = data[:n]
validation_data = data[n:]

# batch execution


In [14]:
batch_size = 4
block_size = 8

def get_batch(split : str) -> tuple:
    data = training_data if split == 'train' else validation_data
    ix = torch.randint(len(data)-block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

In [15]:
x,y = get_batch('train')
print(x)
print(y)

tensor([[ 3627,  2715,  7201,   261, 13857,   558,   220,    17],
        [  484,  4787, 25093,   326,   261,  1647,  1218, 18861],
        [51024,  3101, 54587,  5263,   316,  3411,  4175,   357],
        [ 5621,   558, 18638,    56, 48526, 17546,  3413,    44]])
tensor([[ 2715,  7201,   261, 13857,   558,   220,    17,   398],
        [ 4787, 25093,   326,   261,  1647,  1218, 18861,   261],
        [ 3101, 54587,  5263,   316,  3411,  4175,   357,  1299],
        [  558, 18638,    56, 48526, 17546,  3413,    44, 11503]])
